import pytest

from universal_mcp.applications.utils import app_from_slug
from universal_mcp.utils.testing import check_application_instance

ALL_APPS = [
    "ahrefs",
    "airtable",
    "apollo",
    "asana",
    "aws_s3",
    "bill",
    "box",
    "braze",
    #"cal_com_v2",
    "calendly",
    "canva",
    "clickup",
    "coda",
    "confluence",
    "contentful",
    "crustdata",
    "dialpad",
    "digitalocean",
    "domain_checker",
    "e2b",
    "elevenlabs",
    "exa",
    "falai",
    "figma",
    "file_system",
    "firecrawl",
    "fireflies",
    "fpl",
    "ghost_content",
    "github",
    "gong",
    "google_calendar",
    "google_docs",
    "google_drive",
    "google_gemini",
    "google_mail",
    "google_searchconsole",
    "google_sheet",
    "hashnode",
    "heygen",
    "http_tools",
    "hubspot",
    "jira",
    "klaviyo",
    "linkedin",
    "mailchimp",
    "markitdown",
    "miro",
    "ms_teams",
    "neon",
    "notion",
    "openai",
    "outlook",
    "perplexity",
    "pipedrive",
    "posthog",
    "reddit",
    "replicate",
    "resend",
    "retell",
    "rocketlane",
    "scraper",
    "semanticscholar",
    "semrush",
    "sendgrid",
    "sentry",
    "serpapi",
    "sharepoint",
    "shopify",
    "shortcut",
    "slack",
    "spotify",
    "supabase",
    "tavily",
    "trello",
    "twilio",
    "twitter",
    "unipile",
    "whatsapp",
    "whatsapp_business",
    "wrike",
    "youtube",
    "zenquotes",
]


@pytest.mark.parametrize("app_name", ALL_APPS)
def test_application(app_name):
    app_class = app_from_slug(app_name)
    app_instance = app_class(integration=None)
    check_application_instance(app_instance, app_name)
